Mercury bottom sheet
codelynkslabs/Mercury pull request #5
Opened 2024-03-05 11:35 UTC by sath-eesh

2024-03-06 05:01 UTC, jayahariv requested changes

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercurySearchBarView.swift
> +                              size: config?.searchBarFont.size ?? 14))
use getter functions inside the config itself. 

- it will avoid the optional value checks. `config.font.size`, `config.font.name`

```
var font: Font {
  _font ?? .systemFont(size: 14)
}

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryContentView.swift
> +    var onItemSelected: (() -> Void)? = nil
group the Binding variables

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryContentView.swift
> +    var itemImages: [Image]?
primaryFont 
secondaryFont

titles 
subtitles

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryContentView.swift
> +    var hasTwoLines: Bool = false
not used?

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryContentView.swift
> +//  File.swift
file name wrong?

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +//  File.swift
file name wrong

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +    var searchBarFont: MercuryFont
searchBar is repeating, may be 
```
placeholder
backgroundColor
font

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +    var configSubtitleView: MercurySubtitleConfig? = nil
already declared the subtitle and subtitle font above? is it intentional?

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +    var configSearchBar: MercurySearchBarConfig? = nil
how about we group the primary mandatory fields as direct properties. grouping the optional fields into a config itself. so, not everyone needs to create/update the config?

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +                    .padding(.vertical, 16)
`padding(16)`

2024-03-06 05:01 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +            }
```
if let searchbarEnabled,  searchbarEnabled {
  MercurySearchBar(text: $searchFieldValue,config: configSearchBar)
} else {
  MercurySubTitleView(subTitle: configSubtitleView?.subTitle,
                             subTitleFont: configSubtitleView?.subTitleFont)
}

2024-03-06 05:39 UTC, sath-eesh commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +    var configSubtitleView: MercurySubtitleConfig? = nil
Both are different.

var itemsSubTitle: [String]? = nil,  var itemSubtitleFont: MercuryFont? = nil these two defines the subtitles display  under the items/titles used in 
            MercuryContentView(
                isPresentedPopUp: $isPresentedPopUp,
                selected: $selected,
                titles: items,
                primaryFont: itemFont,
                subtitles: itemsSubTitle,  <--
                secondaryFont: itemSubtitleFont,  <--
                itemImages: itemsImages
            )
            
            
And var configSubtitleView: MercurySubtitleConfig? = nil is used to define the subtitle view display under the main title, used here

MercurySubTitleView(subTitle: configSubtitleView?.subTitle,
                             subTitleFont: configSubtitleView?.subTitleFont)

2024-03-06 11:10 UTC, jayahariv reviewed
Can you add the usage in description

2024-03-06 11:10 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +    var subTitleFont: MercuryFont
`font`

2024-03-06 11:10 UTC, jayahariv commented on Sources/Mercury/BottomSheet/MercuryBottomSheet.swift
> +    var subTitle: String
`text`

2024-03-07 06:02 UTC, jayahariv approved these changes

2024-03-07 06:02 UTC, merged